# Use root/example as user/password credentials
version: '3.1'

services:

 mongo:
    image: mongo
    restart: always
    volumes:
        - ./mongodb_data:/data/db
    networks:
        - my-react-app
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example

 mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        depends_on:
            - mongo
        networks:
            - my-react-app
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

 client:
        #image: mhart/alpine-node:6.8.0
        build: ./client
        restart: always
        ports:
            - "3000:3000"
        working_dir: /client
        volumes:
            - ./client:/client
            - /client/node_modules
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
            - CI=true
        networks:
            - my-react-app
 api:
        #image: yourdockHub/tagname
        build:
            context: ./api/
            dockerfile: api.Dockerfile
        restart: always
        ports:
            - "9000:9000"
        # ExpressJS default port
        volumes:
            - ./api:/api
            - /api/node_modules
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
            - CI=true
        depends_on:
            - mongo
        networks:
            - my-react-app
           


networks:
    my-react-app:
        driver: bridge
        #default is bridge mode